name: yabfc

services:
  app:
    image: ghcr.io/yabfc/yabfc:latest
    container_name: yabfc
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/yabfc/yabfc:latest
    restart: unless-stopped
    ports:
      - 8080:8080
