name: yafc

services:
  app:
    image: ghcr.io/yafc/yafc:latest
    container_name: yafc
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/yafc/yafc:latest
    restart: unless-stopped
    ports:
      - 8080:8080
